import { db } from "./db";
import { vehicles, marketComps, costTemplates, organizations } from "@shared/schema";
import { eq } from "drizzle-orm";

const demoVehicles = [
  {
    orgId: 1, make: "BMW", model: "530d", variant: "xDrive M Sport", year: 2021,
    mileageKm: 78000, enginePower: 286, co2: 152, gearbox: "automatic", fuelType: "diesel",
    color: "Black Sapphire", sourceType: "auction", sourceUrl: "https://auto1.com/demo",
    sourceCountry: "DE", purchasePrice: 28500, purchaseCurrency: "EUR",
    auctionFees: 850, transportCost: 4500, preparationCost: 8000, inspectionCost: 1800,
    otherCosts: 2000, registrationTax: 95000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 285000, resaleNormal: 319000,
    resaleOptimistic: 345000, dealScore: 78, riskFlags: [] as string[],
    status: "evaluating", notes: "Clean Carfax, full BMW service history. M Sport package with adaptive suspension.",
    isDemo: true, imageUrls: ["/images/cars/bmw-530d.jpg"] as string[],
  },
  {
    orgId: 1, make: "Mercedes-Benz", model: "E220d", variant: "AMG Line", year: 2020,
    mileageKm: 95000, enginePower: 194, co2: 138, gearbox: "automatic", fuelType: "diesel",
    color: "Obsidian Black", sourceType: "auction", sourceUrl: "https://bca.com/demo",
    sourceCountry: "DE", purchasePrice: 22000, purchaseCurrency: "EUR",
    auctionFees: 750, transportCost: 4500, preparationCost: 12000, inspectionCost: 1800,
    otherCosts: 3000, registrationTax: 78000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 245000, resaleNormal: 275000,
    resaleOptimistic: 299000, dealScore: 72, riskFlags: ["High mileage"] as string[],
    status: "bid_placed", notes: "AMG Line with Night Package. Some paint correction needed on front bumper.",
    isDemo: true, imageUrls: ["/images/cars/mercedes-e220d.jpg"] as string[],
  },
  {
    orgId: 1, make: "Audi", model: "A6", variant: "50 TDI quattro S-line", year: 2022,
    mileageKm: 45000, enginePower: 286, co2: 168, gearbox: "automatic", fuelType: "diesel",
    color: "Mythos Black", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 35000, purchaseCurrency: "EUR",
    auctionFees: 900, transportCost: 4500, preparationCost: 5000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 125000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 395000, resaleNormal: 435000,
    resaleOptimistic: 465000, dealScore: 82,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/audi-a6.jpg"] as string[],
    notes: "Very low mileage for year. Full Audi service. Bang & Olufsen sound, Matrix LED.",
  },
  {
    orgId: 1, make: "Volkswagen", model: "Tiguan", variant: "2.0 TDI R-Line", year: 2021,
    mileageKm: 62000, enginePower: 200, co2: 158, gearbox: "automatic", fuelType: "diesel",
    color: "Pure White", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 21000, purchaseCurrency: "EUR",
    auctionFees: 650, transportCost: 4500, preparationCost: 6000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 68000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 225000, resaleNormal: 259000,
    resaleOptimistic: 279000, dealScore: 75,
    riskFlags: [] as string[], status: "won", isDemo: true, imageUrls: ["/images/cars/vw-tiguan.jpg"] as string[],
    notes: "R-Line with panoramic roof. Popular model in DK market.",
  },
  {
    orgId: 1, make: "Volvo", model: "XC60", variant: "B5 AWD Inscription", year: 2021,
    mileageKm: 55000, enginePower: 250, co2: 155, gearbox: "automatic", fuelType: "diesel",
    color: "Crystal White", sourceType: "auction", sourceCountry: "SE",
    purchasePrice: 26000, purchaseCurrency: "EUR",
    auctionFees: 800, transportCost: 3500, preparationCost: 7000, inspectionCost: 1800,
    otherCosts: 2000, registrationTax: 88000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 295000, resaleNormal: 329000,
    resaleOptimistic: 359000, dealScore: 76,
    riskFlags: [] as string[], status: "transport", isDemo: true, imageUrls: ["/images/cars/volvo-xc60.jpg"] as string[],
    notes: "Inscription trim with all safety features. Bowers & Wilkins audio.",
  },
  {
    orgId: 1, make: "Porsche", model: "Cayenne", variant: "Coupe", year: 2020,
    mileageKm: 68000, enginePower: 340, co2: 228, gearbox: "automatic", fuelType: "petrol",
    color: "Carrara White", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 52000, purchaseCurrency: "EUR",
    auctionFees: 1200, transportCost: 5000, preparationCost: 15000, inspectionCost: 2500,
    otherCosts: 3000, registrationTax: 285000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 695000, resaleNormal: 749000,
    resaleOptimistic: 795000, dealScore: 55,
    riskFlags: ["High capital binding"] as string[], status: "evaluating", isDemo: true,
    imageUrls: ["/images/cars/porsche-cayenne.jpg"] as string[],
    notes: "High-value unit. Sport Chrono, PASM, 21-inch wheels. Full Porsche service.",
  },
  {
    orgId: 1, make: "BMW", model: "X3", variant: "xDrive20d M Sport", year: 2022,
    mileageKm: 38000, enginePower: 190, co2: 148, gearbox: "automatic", fuelType: "diesel",
    color: "Phytonic Blue", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 30000, purchaseCurrency: "EUR",
    auctionFees: 800, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 82000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 345000, resaleNormal: 379000,
    resaleOptimistic: 399000, dealScore: 85,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/bmw-x3.jpg"] as string[],
    notes: "Top scorer. Low km, popular color and spec. M Sport with Vernasca leather.",
  },
  {
    orgId: 1, make: "Mercedes-Benz", model: "GLC 300d", variant: "4MATIC AMG", year: 2021,
    mileageKm: 72000, enginePower: 245, co2: 162, gearbox: "automatic", fuelType: "diesel",
    color: "Selenite Grey", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 32000, purchaseCurrency: "EUR",
    auctionFees: 850, transportCost: 4500, preparationCost: 9000, inspectionCost: 1800,
    otherCosts: 2000, registrationTax: 98000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 365000, resaleNormal: 399000,
    resaleOptimistic: 429000, dealScore: 71,
    riskFlags: [] as string[], status: "preparation", isDemo: true, imageUrls: ["/images/cars/mercedes-glc.jpg"] as string[],
    notes: "AMG package, Burmester sound, 360 camera. Ready after paint touch-up.",
  },
  {
    orgId: 1, make: "Skoda", model: "Octavia", variant: "2.0 TDI Style", year: 2022,
    mileageKm: 42000, enginePower: 150, co2: 118, gearbox: "automatic", fuelType: "diesel",
    color: "Moon White", sourceType: "manual", sourceCountry: "PL",
    purchasePrice: 14000, purchaseCurrency: "EUR",
    auctionFees: 400, transportCost: 3000, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 22000, vatType: "margin" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 155000, resaleNormal: 175000,
    resaleOptimistic: 189000, dealScore: 88,
    riskFlags: [] as string[], status: "ready_for_sale", isDemo: true, imageUrls: ["/images/cars/skoda-octavia.jpg"] as string[],
    notes: "Excellent budget option. High ROI. Very popular in DK. Clean car.",
  },
  {
    orgId: 1, make: "Tesla", model: "Model 3", variant: "Long Range AWD", year: 2021,
    mileageKm: 48000, enginePower: 346, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Pearl White", sourceType: "auction", sourceCountry: "NL",
    purchasePrice: 27000, purchaseCurrency: "EUR",
    auctionFees: 700, transportCost: 4000, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 245000, resaleNormal: 269000,
    resaleOptimistic: 289000, dealScore: 90,
    riskFlags: [] as string[], status: "online", isDemo: true, imageUrls: ["/images/cars/tesla-model3.jpg"] as string[],
    notes: "Zero registration tax for EVs. Highest deal score in demo. Full autopilot.",
  },
  {
    orgId: 1, make: "Peugeot", model: "3008", variant: "1.5 BlueHDi GT", year: 2020,
    mileageKm: 112000, enginePower: 130, co2: 128, gearbox: "automatic", fuelType: "diesel",
    color: "Amazonite Grey", sourceType: "manual", sourceCountry: "FR",
    purchasePrice: 13500, purchaseCurrency: "EUR",
    auctionFees: 500, transportCost: 5000, preparationCost: 8000, inspectionCost: 1800,
    otherCosts: 2000, registrationTax: 45000, vatType: "unknown" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 145000, resaleNormal: 165000,
    resaleOptimistic: 179000, dealScore: 35,
    riskFlags: ["High mileage", "Unknown VAT type"] as string[], status: "evaluating", isDemo: true,
    imageUrls: ["/images/cars/peugeot-3008.jpg"] as string[],
    notes: "High km but priced accordingly. VAT status needs verification. GT trim popular.",
  },
  {
    orgId: 1, make: "Land Rover", model: "Range Rover Sport", variant: "3.0 SDV6 HSE", year: 2019,
    mileageKm: 92000, enginePower: 306, co2: 199, gearbox: "automatic", fuelType: "diesel",
    color: "Santorini Black", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 38000, purchaseCurrency: "EUR",
    auctionFees: 1100, transportCost: 5500, preparationCost: 18000, inspectionCost: 2500,
    otherCosts: 5000, registrationTax: 195000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 495000, resaleNormal: 545000,
    resaleOptimistic: 589000, dealScore: 42,
    riskFlags: ["High mileage", "High capital binding"] as string[], status: "found", isDemo: true,
    imageUrls: ["/images/cars/range-rover-sport.jpg"] as string[],
    notes: "High risk, high reward. Known for expensive repairs. Full service required.",
  },
  {
    orgId: 1, make: "Audi", model: "Q5", variant: "40 TDI quattro S-line", year: 2022,
    mileageKm: 35000, enginePower: 204, co2: 152, gearbox: "automatic", fuelType: "diesel",
    color: "Navarra Blue", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 32000, purchaseCurrency: "EUR",
    auctionFees: 850, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 92000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 355000, resaleNormal: 389000,
    resaleOptimistic: 415000, dealScore: 80,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/audi-q5.jpg"] as string[],
    notes: "Low km Q5 S-line. Virtual cockpit, Matrix LED. Strong resale in DK.",
  },
  {
    orgId: 1, make: "Toyota", model: "RAV4", variant: "2.5 Hybrid AWD", year: 2021,
    mileageKm: 52000, enginePower: 222, co2: 119, gearbox: "automatic", fuelType: "hybrid",
    color: "Dynamic Blue", sourceType: "manual", sourceCountry: "BE",
    purchasePrice: 24000, purchaseCurrency: "EUR",
    auctionFees: 600, transportCost: 4000, preparationCost: 3500, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 28000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 265000, resaleNormal: 295000,
    resaleOptimistic: 319000, dealScore: 84,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/toyota-rav4.jpg"] as string[],
    notes: "Low registration tax due to hybrid. Very reliable. Strong demand.",
  },
  {
    orgId: 1, make: "BMW", model: "520d", variant: "Touring M Sport", year: 2020,
    mileageKm: 118000, enginePower: 190, co2: 142, gearbox: "automatic", fuelType: "diesel",
    color: "Mineral Grey", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 19000, purchaseCurrency: "EUR",
    auctionFees: 650, transportCost: 4500, preparationCost: 12000, inspectionCost: 1800,
    otherCosts: 3000, registrationTax: 72000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 225000, resaleNormal: 255000,
    resaleOptimistic: 279000, dealScore: 58,
    riskFlags: ["High mileage"] as string[], status: "sold", isDemo: true, imageUrls: ["/images/cars/bmw-520d-touring.jpg"] as string[],
    notes: "Sold for 262,000 DKK. Good profit despite high km. Touring very popular.",
  },
  {
    orgId: 1, make: "Volkswagen", model: "Golf GTD", variant: "2.0 TDI DSG", year: 2020,
    mileageKm: 72000, enginePower: 200, co2: 130, gearbox: "automatic", fuelType: "diesel",
    color: "Atlantic Blue", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 18500, purchaseCurrency: "EUR",
    auctionFees: 600, transportCost: 4500, preparationCost: 5000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 55000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 195000, resaleNormal: 219000,
    resaleOptimistic: 239000, dealScore: 79,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/vw-golf-gtd.jpg"] as string[],
    notes: "GTD is popular daily driver. Good power with low tax. Virtual cockpit, ACC.",
  },
  {
    orgId: 1, make: "Mercedes-Benz", model: "C300d", variant: "AMG Line", year: 2022,
    mileageKm: 32000, enginePower: 265, co2: 145, gearbox: "automatic", fuelType: "diesel",
    color: "High-tech Silver", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 33000, purchaseCurrency: "EUR",
    auctionFees: 900, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 105000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 375000, resaleNormal: 415000,
    resaleOptimistic: 445000, dealScore: 83,
    riskFlags: [] as string[], status: "evaluating", isDemo: true, imageUrls: ["/images/cars/mercedes-c300d.jpg"] as string[],
    notes: "New W206. Very low km, AMG Line, Digital Light. Strong demand in DK.",
  },
  {
    orgId: 1, make: "Audi", model: "A4 Avant", variant: "40 TDI S-line", year: 2021,
    mileageKm: 85000, enginePower: 204, co2: 140, gearbox: "automatic", fuelType: "diesel",
    color: "Glacier White", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 22500, purchaseCurrency: "EUR",
    auctionFees: 700, transportCost: 4500, preparationCost: 6000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 72000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 249000, resaleNormal: 279000,
    resaleOptimistic: 299000, dealScore: 73,
    riskFlags: [] as string[], status: "won", isDemo: true, imageUrls: ["/images/cars/audi-a4-avant.jpg"] as string[],
    notes: "Avant/stationcar very popular in DK. S-line with Virtual Cockpit, B&O.",
  },
  {
    orgId: 1, make: "BMW", model: "iX3", variant: "Impressive", year: 2022,
    mileageKm: 28000, enginePower: 286, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Mineral White", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 31000, purchaseCurrency: "EUR",
    auctionFees: 800, transportCost: 4500, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 285000, resaleNormal: 315000,
    resaleOptimistic: 339000, dealScore: 92,
    riskFlags: [] as string[], status: "transport", isDemo: true, imageUrls: ["/images/cars/bmw-ix3.jpg"] as string[],
    notes: "Zero reg tax EV. Very strong resale. 461 km range. Impressive trim.",
  },
  {
    orgId: 1, make: "Hyundai", model: "Tucson", variant: "1.6 T-GDi HEV Premium", year: 2022,
    mileageKm: 35000, enginePower: 230, co2: 135, gearbox: "automatic", fuelType: "hybrid",
    color: "Shadow Grey", sourceType: "manual", sourceCountry: "NL",
    purchasePrice: 23000, purchaseCurrency: "EUR",
    auctionFees: 600, transportCost: 4000, preparationCost: 4000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 38000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 249000, resaleNormal: 275000,
    resaleOptimistic: 295000, dealScore: 81,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/hyundai-tucson.jpg"] as string[],
    notes: "New design Tucson hybrid. Low tax due to hybrid. Very popular model.",
  },
  {
    orgId: 1, make: "Volvo", model: "XC40", variant: "T5 Recharge PHEV", year: 2022,
    mileageKm: 25000, enginePower: 262, co2: 29, gearbox: "automatic", fuelType: "hybrid",
    color: "Fjord Blue", sourceType: "auction", sourceCountry: "SE",
    purchasePrice: 28000, purchaseCurrency: "EUR",
    auctionFees: 750, transportCost: 3500, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 12000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 285000, resaleNormal: 315000,
    resaleOptimistic: 339000, dealScore: 87,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/volvo-xc40.jpg"] as string[],
    notes: "PHEV with very low reg tax. Popular in DK. Volvo safety. Low km.",
  },
  {
    orgId: 1, make: "BMW", model: "330e", variant: "Touring M Sport", year: 2022,
    mileageKm: 30000, enginePower: 292, co2: 32, gearbox: "automatic", fuelType: "hybrid",
    color: "Black Sapphire", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 34000, purchaseCurrency: "EUR",
    auctionFees: 850, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 18000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 345000, resaleNormal: 379000,
    resaleOptimistic: 405000, dealScore: 86,
    riskFlags: [] as string[], status: "evaluating", isDemo: true, imageUrls: ["/images/cars/bmw-330e.jpg"] as string[],
    notes: "PHEV Touring M Sport. Extremely low reg tax. Strong demand. Full spec.",
  },
  {
    orgId: 1, make: "Seat", model: "Leon", variant: "1.5 TSI FR", year: 2021,
    mileageKm: 55000, enginePower: 150, co2: 122, gearbox: "manual", fuelType: "petrol",
    color: "Desire Red", sourceType: "manual", sourceCountry: "DE",
    purchasePrice: 12000, purchaseCurrency: "EUR",
    auctionFees: 400, transportCost: 4500, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 35000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 139000, resaleNormal: 159000,
    resaleOptimistic: 175000, dealScore: 77,
    riskFlags: [] as string[], status: "ready_for_sale", isDemo: true, imageUrls: ["/images/cars/seat-leon.jpg"] as string[],
    notes: "Budget-friendly FR trim. Manual gearbox limits DK demand slightly.",
  },
  {
    orgId: 1, make: "Mercedes-Benz", model: "GLE 350d", variant: "4MATIC AMG Line", year: 2021,
    mileageKm: 65000, enginePower: 272, co2: 195, gearbox: "automatic", fuelType: "diesel",
    color: "Obsidian Black", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 42000, purchaseCurrency: "EUR",
    auctionFees: 1100, transportCost: 5000, preparationCost: 10000, inspectionCost: 2500,
    otherCosts: 3000, registrationTax: 175000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 545000, resaleNormal: 595000,
    resaleOptimistic: 635000, dealScore: 62,
    riskFlags: ["High capital binding"] as string[], status: "bid_placed", isDemo: true, imageUrls: ["/images/cars/mercedes-gle.jpg"] as string[],
    notes: "Premium SUV. AMG Line, air suspension, Burmester 3D. High capital needed.",
  },
  {
    orgId: 1, make: "Kia", model: "EV6", variant: "Long Range AWD GT-Line", year: 2022,
    mileageKm: 22000, enginePower: 325, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Yacht Blue", sourceType: "auction", sourceCountry: "NL",
    purchasePrice: 35000, purchaseCurrency: "EUR",
    auctionFees: 800, transportCost: 4000, preparationCost: 2500, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 329000, resaleNormal: 365000,
    resaleOptimistic: 389000, dealScore: 91,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/kia-ev6.jpg"] as string[],
    notes: "Zero reg tax. Award-winning EV. 528 km range. Very strong demand.",
  },
  {
    orgId: 1, make: "Ford", model: "Mustang Mach-E", variant: "Extended Range AWD", year: 2022,
    mileageKm: 18000, enginePower: 351, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Grabber Blue", sourceType: "auction", sourceCountry: "NO",
    purchasePrice: 33000, purchaseCurrency: "EUR",
    auctionFees: 750, transportCost: 5500, preparationCost: 2000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 305000, resaleNormal: 339000,
    resaleOptimistic: 365000, dealScore: 89,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/ford-mustang-mache.jpg"] as string[],
    notes: "Zero reg tax EV from Norway. Extended range. Popular crossover.",
  },
  {
    orgId: 1, make: "Volkswagen", model: "ID.4", variant: "Pro Performance", year: 2022,
    mileageKm: 30000, enginePower: 204, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Moonstone Grey", sourceType: "manual", sourceCountry: "DE",
    purchasePrice: 24000, purchaseCurrency: "EUR",
    auctionFees: 600, transportCost: 4500, preparationCost: 2500, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 219000, resaleNormal: 249000,
    resaleOptimistic: 269000, dealScore: 86,
    riskFlags: [] as string[], status: "evaluating", isDemo: true, imageUrls: ["/images/cars/vw-id4.jpg"] as string[],
    notes: "Zero reg tax. VW reliability. 520 km range. Solid family EV choice.",
  },
  {
    orgId: 1, make: "BMW", model: "M340i", variant: "xDrive", year: 2021,
    mileageKm: 48000, enginePower: 374, co2: 175, gearbox: "automatic", fuelType: "petrol",
    color: "Tanzanite Blue", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 38000, purchaseCurrency: "EUR",
    auctionFees: 950, transportCost: 4500, preparationCost: 5000, inspectionCost: 1800,
    otherCosts: 2000, registrationTax: 195000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 475000, resaleNormal: 525000,
    resaleOptimistic: 565000, dealScore: 60,
    riskFlags: ["High capital binding"] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/bmw-m340i.jpg"] as string[],
    notes: "Performance sedan. M Sport diff, Harman Kardon. High reg tax is the challenge.",
  },
  {
    orgId: 1, make: "Skoda", model: "Superb", variant: "2.0 TDI Combi Style", year: 2021,
    mileageKm: 68000, enginePower: 150, co2: 125, gearbox: "automatic", fuelType: "diesel",
    color: "Lava Blue", sourceType: "manual", sourceCountry: "PL",
    purchasePrice: 16000, purchaseCurrency: "EUR",
    auctionFees: 450, transportCost: 3000, preparationCost: 4000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 32000, vatType: "margin" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 179000, resaleNormal: 205000,
    resaleOptimistic: 225000, dealScore: 83,
    riskFlags: [] as string[], status: "preparation", isDemo: true, imageUrls: ["/images/cars/skoda-superb.jpg"] as string[],
    notes: "Great value. Combi/wagon popular in DK. Spacious and practical. From Poland.",
  },
  {
    orgId: 1, make: "Audi", model: "e-tron", variant: "55 quattro S-line", year: 2021,
    mileageKm: 42000, enginePower: 408, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Chronos Grey", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 36000, purchaseCurrency: "EUR",
    auctionFees: 900, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 325000, resaleNormal: 365000,
    resaleOptimistic: 395000, dealScore: 88,
    riskFlags: [] as string[], status: "online", isDemo: true, imageUrls: ["/images/cars/audi-etron.jpg"] as string[],
    notes: "Zero reg tax. Premium EV SUV. S-line, air suspension, Bang & Olufsen.",
  },
  {
    orgId: 1, make: "Renault", model: "Megane", variant: "1.5 dCi Zen", year: 2019,
    mileageKm: 135000, enginePower: 115, co2: 110, gearbox: "manual", fuelType: "diesel",
    color: "Iron Blue", sourceType: "manual", sourceCountry: "FR",
    purchasePrice: 7500, purchaseCurrency: "EUR",
    auctionFees: 300, transportCost: 5000, preparationCost: 5000, inspectionCost: 1500,
    otherCosts: 1500, registrationTax: 18000, vatType: "unknown" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 79000, resaleNormal: 95000,
    resaleOptimistic: 109000, dealScore: 28,
    riskFlags: ["High mileage", "Unknown VAT type", "Old vehicle"] as string[], status: "found",
    isDemo: true, imageUrls: ["/images/cars/renault-megane.jpg"] as string[],
    notes: "Very high km. Unknown VAT. Limited DK demand for Renault. Budget segment only.",
  },
  {
    orgId: 1, make: "Porsche", model: "Taycan", variant: "4S Performance Plus", year: 2022,
    mileageKm: 20000, enginePower: 530, co2: 0, gearbox: "automatic", fuelType: "electric",
    color: "Frozen Blue", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 68000, purchaseCurrency: "EUR",
    auctionFees: 1500, transportCost: 5000, preparationCost: 5000, inspectionCost: 2500,
    otherCosts: 2000, registrationTax: 0, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 595000, resaleNormal: 649000,
    resaleOptimistic: 695000, dealScore: 72,
    riskFlags: ["High capital binding"] as string[], status: "evaluating", isDemo: true, imageUrls: ["/images/cars/porsche-taycan.jpg"] as string[],
    notes: "Zero reg tax. Ultra-premium EV. High capital but strong resale in DK luxury segment.",
  },
  {
    orgId: 1, make: "Toyota", model: "Corolla", variant: "1.8 Hybrid Active Touring", year: 2022,
    mileageKm: 28000, enginePower: 122, co2: 96, gearbox: "automatic", fuelType: "hybrid",
    color: "Celestite Grey", sourceType: "manual", sourceCountry: "BE",
    purchasePrice: 18000, purchaseCurrency: "EUR",
    auctionFees: 500, transportCost: 4000, preparationCost: 2500, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 15000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 189000, resaleNormal: 215000,
    resaleOptimistic: 235000, dealScore: 85,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/toyota-corolla.jpg"] as string[],
    notes: "Very low reg tax hybrid. Toyota reliability. Touring/wagon popular in DK.",
  },
  {
    orgId: 1, make: "Mazda", model: "CX-5", variant: "2.2 Skyactiv-D Optimum AWD", year: 2021,
    mileageKm: 62000, enginePower: 184, co2: 148, gearbox: "automatic", fuelType: "diesel",
    color: "Soul Red Crystal", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 20000, purchaseCurrency: "EUR",
    auctionFees: 600, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 62000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 225000, resaleNormal: 255000,
    resaleOptimistic: 275000, dealScore: 76,
    riskFlags: [] as string[], status: "bid_placed", isDemo: true, imageUrls: ["/images/cars/mazda-cx5.jpg"] as string[],
    notes: "Soul Red Crystal metallic paint is very desirable. AWD for DK winters.",
  },
  {
    orgId: 1, make: "Cupra", model: "Formentor", variant: "2.0 TSI VZ 310 4Drive", year: 2022,
    mileageKm: 25000, enginePower: 310, co2: 176, gearbox: "automatic", fuelType: "petrol",
    color: "Magnetic Tech Grey", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 28000, purchaseCurrency: "EUR",
    auctionFees: 750, transportCost: 4500, preparationCost: 4000, inspectionCost: 1800,
    otherCosts: 1500, registrationTax: 145000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 335000, resaleNormal: 369000,
    resaleOptimistic: 395000, dealScore: 52,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/cupra-formentor.jpg"] as string[],
    notes: "High-performance crossover. High reg tax due to petrol. Growing brand in DK.",
  },
  {
    orgId: 1, make: "BMW", model: "X1", variant: "xDrive25e PHEV", year: 2022,
    mileageKm: 20000, enginePower: 220, co2: 38, gearbox: "automatic", fuelType: "hybrid",
    color: "Alpine White", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 25000, purchaseCurrency: "EUR",
    auctionFees: 700, transportCost: 4500, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 15000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 269000, resaleNormal: 299000,
    resaleOptimistic: 319000, dealScore: 87,
    riskFlags: [] as string[], status: "won", isDemo: true, imageUrls: ["/images/cars/bmw-x1.jpg"] as string[],
    notes: "PHEV with minimal reg tax. Compact SUV very popular in DK. Low km.",
  },
  {
    orgId: 1, make: "Mercedes-Benz", model: "A250e", variant: "AMG Line PHEV", year: 2022,
    mileageKm: 22000, enginePower: 218, co2: 25, gearbox: "automatic", fuelType: "hybrid",
    color: "Cosmos Black", sourceType: "auction", sourceCountry: "DE",
    purchasePrice: 24000, purchaseCurrency: "EUR",
    auctionFees: 650, transportCost: 4500, preparationCost: 3000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 10000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 229000, resaleNormal: 259000,
    resaleOptimistic: 279000, dealScore: 84,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/mercedes-a250e.jpg"] as string[],
    notes: "PHEV AMG Line. Very low reg tax. Compact but premium. Low km.",
  },
  {
    orgId: 1, make: "Nissan", model: "Qashqai", variant: "1.3 DIG-T Tekna", year: 2021,
    mileageKm: 58000, enginePower: 158, co2: 140, gearbox: "automatic", fuelType: "petrol",
    color: "Magnetic Blue", sourceType: "manual", sourceCountry: "NL",
    purchasePrice: 17000, purchaseCurrency: "EUR",
    auctionFees: 500, transportCost: 4000, preparationCost: 4000, inspectionCost: 1500,
    otherCosts: 1000, registrationTax: 52000, vatType: "eu_reverse_charge" as const,
    vatAmount: 0, vatReturn: 0, resaleConservative: 179000, resaleNormal: 205000,
    resaleOptimistic: 225000, dealScore: 70,
    riskFlags: [] as string[], status: "found", isDemo: true, imageUrls: ["/images/cars/nissan-qashqai.jpg"] as string[],
    notes: "New generation Qashqai. Tekna is top trim. Solid DK market presence.",
  },
];

function generateComps(vehicleId: number, make: string, model: string, year: number, basePrice: number, orgId: number): any[] {
  const comps = [];
  const count = 12 + Math.floor(Math.random() * 18);
  for (let i = 0; i < count; i++) {
    const yearVariation = Math.random() > 0.3 ? 0 : (Math.random() > 0.5 ? 1 : -1);
    const priceVariation = 0.75 + Math.random() * 0.5;
    const kmVariation = 0.5 + Math.random() * 1.5;
    const locations = [
      "Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers",
      "Kolding", "Horsens", "Roskilde", "Herning", "Vejle", "Fredericia",
      "Viborg", "Silkeborg", "Svendborg", "Holstebro"
    ];
    const sources = ["bilbasen.dk", "mobile.de", "autoscout24.dk", "autouncle.dk", "bilhandel.dk"];
    comps.push({
      vehicleId,
      orgId,
      make,
      model,
      variant: "",
      year: year + yearVariation,
      mileageKm: Math.round(70000 * kmVariation),
      price: Math.round(basePrice * priceVariation),
      currency: "DKK",
      source: sources[Math.floor(Math.random() * sources.length)],
      location: locations[Math.floor(Math.random() * locations.length)],
      isDemo: true,
    });
  }
  return comps;
}

const demoCostTemplates = [
  { name: "Standard DK Import", marketCountry: "DK", currency: "DKK", transport: 4500, preparation: 8000, inspection: 1800, plates: 1200, buffer: 3000, isDefault: true, isDemo: true },
  { name: "Premium DK Import", marketCountry: "DK", currency: "DKK", transport: 5500, preparation: 15000, inspection: 2500, plates: 1200, buffer: 5000, isDefault: false, isDemo: true },
  { name: "Budget DK Import", marketCountry: "DK", currency: "DKK", transport: 3500, preparation: 4000, inspection: 1500, plates: 1200, buffer: 2000, isDefault: false, isDemo: true },
  { name: "Damage Buffer DK", marketCountry: "DK", currency: "DKK", transport: 4500, preparation: 18000, inspection: 2500, plates: 1200, buffer: 8000, isDefault: false, isDemo: true },
  { name: "Standard DE Domestic", marketCountry: "DE", currency: "EUR", transport: 500, preparation: 1500, inspection: 200, plates: 100, buffer: 500, isDefault: true, isDemo: true },
  { name: "Standard PL Import", marketCountry: "PL", currency: "PLN", transport: 3000, preparation: 5000, inspection: 800, plates: 500, buffer: 2000, isDefault: true, isDemo: true },
  { name: "Standard NL Import", marketCountry: "NL", currency: "EUR", transport: 800, preparation: 2000, inspection: 300, plates: 150, buffer: 800, isDefault: true, isDemo: true },
  { name: "Standard SE Import", marketCountry: "SE", currency: "SEK", transport: 8000, preparation: 12000, inspection: 2000, plates: 1500, buffer: 4000, isDefault: true, isDemo: true },
  { name: "Standard NO Import", marketCountry: "NO", currency: "NOK", transport: 9000, preparation: 15000, inspection: 2500, plates: 2000, buffer: 5000, isDefault: true, isDemo: true },
  { name: "Standard BE Import", marketCountry: "BE", currency: "EUR", transport: 1000, preparation: 2500, inspection: 300, plates: 200, buffer: 800, isDefault: true, isDemo: true },
  { name: "Standard FR Import", marketCountry: "FR", currency: "EUR", transport: 1200, preparation: 3000, inspection: 400, plates: 250, buffer: 1000, isDefault: true, isDemo: true },
];

export async function seedDemoData() {
  try {
    const existing = await db.select().from(vehicles).where(eq(vehicles.isDemo, true)).limit(1);
    if (existing.length > 0) {
      return;
    }

    console.log("Seeding demo data...");

    const [demoOrg] = await db.insert(organizations).values({
      name: "Demo Organization",
      slug: "demo-org",
      plan: "free",
      status: "active",
      mode: "demo",
      marketCountry: "DK",
      language: "en",
    }).returning();

    for (const vehicleData of demoVehicles) {
      vehicleData.orgId = demoOrg.id;
      const [created] = await db.insert(vehicles).values(vehicleData).returning();

      const resalePrice = vehicleData.resaleNormal || 300000;
      const comps = generateComps(created.id, vehicleData.make, vehicleData.model, vehicleData.year, resalePrice, demoOrg.id);
      if (comps.length > 0) {
        await db.insert(marketComps).values(comps);
      }
    }

    for (const template of demoCostTemplates) {
      await db.insert(costTemplates).values({ ...template, orgId: demoOrg.id });
    }

    console.log(`Seeded ${demoVehicles.length} demo vehicles with market comps and ${demoCostTemplates.length} cost templates`);
  } catch (error) {
    console.error("Error seeding demo data:", error);
  }
}
